### ISSUE TITLE
update failed for AnAction with ID=ultimatepastebin.createPaste: com/intellij/openapi/actionSystem/DataKeys

### ISSUE THREAD

**Issue by Plato2013** [kennedyoliveira/ultimate-pastebin-intellij-plugin#14]
Hi,

with the newest version of the plugin the problem seems to be back. 

PhpStorm 2016.3.1 for Mac OS
Build #PS-163.9735.1, built on December 6, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Ultimate PasteBin 1.5.0

http://pastebin.com/C4npnm25

**Comment by kennedyoliveira** [comment]
Hey @Plato2013! I'll look at it, thanks for reporting.

**Comment by kennedyoliveira** [comment]
Hey @Plato2013, i'm sorry i'm taking so long to fix it, i had a very busy week, i'll fix it this weekend, it's the same problem you faced in #2, somehow i lose the fix i did by using multiple versions of the plugin, i'm fix it today.

**Comment by kennedyoliveira** [comment]
Just uploaded a new version fixing the issue, check it out v1.5.1

**Comment by Plato2013** [comment]
Thank you very much for the fast fix! Will try as soon as the update is available within the IDE.

**Comment by kennedyoliveira** [comment]
@Plato2013, now jetbrains is reviewing new updates, they said it should take up to 2 business days. I'm reopening because git automatic closes the issues after a comment with "Fix".

**Comment by kennedyoliveira** [comment]
@Plato2013 the new version is available within the ide!

**Comment by Plato2013** [comment]
@kennedyoliveira Sorry, took a while until it was available for me and I could test it. Works very well again. Thank you very much!
