### ISSUE TITLE
Error while fetching data from PasteBin

### ISSUE THREAD

**Issue by TechnoDexx** [kennedyoliveira/ultimate-pastebin-intellij-plugin#15]
Ultimate PasteBin
		Error while fetching data from PasteBin
		Unknow error
on IDE loading
Check account Credentials - Valid, Re-Install plugin not solved this problem.
Update: Paste creates, but Validate Account Credentials goes to infinnite loop.

PyCharm Community Edition 2016.3.2
Build #PC-163.10154.50, built on December 28, 2016
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
OS: Windows 10

**Comment by TechnoDexx** [comment]
Issue solved.

**Comment by kennedyoliveira** [comment]
hey @TechnoDexx, sorry for the delay.
I'm glad that you worked out a solution, would you mind sharing here the solution? If another person have the same problem, that could help them.
Thank you.

**Comment by TechnoDexx** [comment]
@kennedyoliveira I am change password on Pastebin.com. So simple solution
