### ISSUE TITLE
Sync with Pastebin

### ISSUE THREAD

**Issue by efinder2** [kennedyoliveira/ultimate-pastebin-intellij-plugin#18]
Please make it possible to sync a file automaticly to pastebin (changes to pastebin).
The built in editor of Pastebin is ... not so good.
It would be awesome, If I could use IntelliJ for editing my Pastes

**Comment by kennedyoliveira** [comment]
Hey! @efinder2 that would be cool, but unfortunatelly, pastebin doesn't provide an update API, so i can't implement it.

**Comment by kennedyoliveira** [comment]
Closing this issue because it's not possible to implement currently.
