### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by ptogladif** [kennedyoliveira/ultimate-pastebin-intellij-plugin#22]
the credentials are correct but it says that are wrong

**Comment by ptogladif** [comment]
Bad API request, use POST request, not GET

**Comment by ptogladif** [comment]
![image](https://user-images.githubusercontent.com/10712577/92109213-8818b800-ede0-11ea-83a4-d6eca9abbb54.png)

**Comment by piotr-janik** [comment]
> the credentials are correct but it says that are wrong

![obraz](https://user-images.githubusercontent.com/4653416/89119135-103b3300-d4ac-11ea-99a3-c3998f78975d.png)

**Comment by bshuler** [comment]
I test the parameters in the url using curl, and it works fine, ant solution here?

**Comment by mlsquires** [comment]
I'm in the same boat - correct username/password/dev key but plugin says not valid.

This pretty much makes the plugin useless.

Just looked at the commits. Nothing has been done here since 2018. Abandoned?

**Comment by ptogladif** [comment]
Dont use it anymore...
