### ISSUE TITLE
Use HTTPS when available

### ISSUE THREAD

**Issue by jcassee** [kennedyoliveira/ultimate-pastebin-intellij-plugin#3]
If the user has a Pastebin pro account, the communication can be over HTTPS. It would be nice if the plugin would handle that. (I would be inclined to take a stab at it if you can point me to where the connection is made.)

**Comment by kennedyoliveira** [comment]
Hey @jcassee! Thank you for the feedback, i forgot about the HTTPS for PRO users, and yes, it would be nice to use indeed, this week i'm very busy and going in a little vacation tomorrow, so i can't implement it, just next week.

If you wanna give a shot, the communication with the API is handled in another project, [pastebin4j](https://github.com/kennedyoliveira/pastebin4j), you can send a pull request and if everything is OK i merge it and update the plugin with the new implementation.

The logic is handled in the class `com.github.kennedyoliveira.pastebin4j.api.PasteBinApiImpl`.

Thank you!
