### ISSUE TITLE
Font settings not correctly applyed

### ISSUE THREAD

**Issue by Kendos-Kenlen** [kennedyoliveira/ultimate-pastebin-intellij-plugin#4]
Hi,

The preview paste panel don't use font settings set in **colors & fonts**. If I'm right, it's the interface font which is used instead of the editor one, so it's not a monospaced font and if ligatures are enabled in the editor (as well as size config and others options), they are not applied in the preview panel.

**Comment by kennedyoliveira** [comment]
Hi @Kendos-Kenlen!
Thanks for the report, i'll check
