### ISSUE TITLE
Use IntelliJ' password manager to store password

### ISSUE THREAD

**Issue by GauthierPLM** [kennedyoliveira/ultimate-pastebin-intellij-plugin#6]
Hi,

Currently, password are stored in plain text in Ultimate Pastebin' configuration file. It's a very bad thing as it's easy for an external user to find it (if config file is involuntarily shared or committed for exemple).

IntelliJ has a password manager which encrypt and store passwords. The plugin should use it to avoid security problems.

**Comment by kennedyoliveira** [comment]
@Kendos-Kenlen, yeah, i forgot about the password manager, i'll check if i can get some documentation on how to use it and implement this way.
Thank you for your feedback and sugestion!

**Comment by Kendos-Kenlen** [comment]
Hi,

I already tried to find a way to store password when I was working on my plugin, however there is no documentation available for the moment. i opened [an issue](https://youtrack.jetbrains.com/issue/IJSDK-41) to ask JetBrains to provide some documentation about it.

The best way is to look in the Git plugin source code I think. I'm curious about it too.

**Comment by kennedyoliveira** [comment]
@Kendos-Kenlen,

thanks for the suggestions, i searched a little and still didn't find anything about it, i'll follow your issue, hope they create some documentation. 

Anyway, i'm gonna look at the git plugin.

**Comment by kennedyoliveira** [comment]
hey @Kendos-Kenlen, sorry for the delay, i implemented your suggestion along with some code refactoring, would you mind testing it before i release and providing a feedback? I would appreciate! Thank you!

**Comment by Kendos-Kenlen** [comment]
Hi ! Sorry, I was busy too, finally in holidays ! 💃 
I tested it, and there is just one problem : the password manager ask for unlocking during IDE booting. It should ask for unlocking only when someone try to paste something, after pressing the "Ok" button of the Paste window.

**Comment by kennedyoliveira** [comment]
Hi @Kendos-Kenlen, thanks for the feedback!

It asks for password because when IntelliJ loads the plugin it fetches the pastes to show in the tool window, i can't change it, maybe i can delay until open a project, but can't delay until you press OK to create a paste.

**Comment by Kendos-Kenlen** [comment]
Ah yeah, I forget that... You can't fetch pastes only when the tool window is opened ? When I wrote my plugin, I only fetched logs in my tool window when it was required.

**Comment by kennedyoliveira** [comment]
@Kendos-Kenlen it's a good suggestion, i guess it's fine to implement that way.

**Comment by karanrajpal14** [comment]
Any chance you can change this behavior? It's tedious to type in the password every time I open the IDE as I have a fairly long password.

**Comment by kennedyoliveira** [comment]
@karanrajpal14 fixed in the last version, 1.5.2

**Comment by karanrajpal14** [comment]
Great! Thank you so much @kennedyoliveira

**Comment by kennedyoliveira** [comment]
you are welcome @karanrajpal14 , i'm closing the issue, if you have any more feedback feel free to open more issues or even reopen this one :)
