### ISSUE TITLE
Pastebin4J is not present in the repository

### ISSUE THREAD

**Issue by Kendos-Kenlen** [kennedyoliveira/ultimate-pastebin-intellij-plugin#7]
Hi,

The pastebin4J lib isn't present in the repo, so when cloning it, it creates broken paths and the plugin can't be built.
Could you add your ```lib``` folder in the repository or provide a way to get it easily?

Sincerely,

**Comment by kennedyoliveira** [comment]
Hi @Kendos-Kenlen,

very weird, IntelliJ should download it automatically, since it's available in maven central, anyway, pastebin4j is another project mine, you can checkout it here [pastebin4j](https://github.com/kennedyoliveira/pastebin4j).
